spring:
  application:
    name: demo-micrometer-brave-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:28761/eureka/
server:
  port: 28081

management:
  zipkin:
    tracing:
      # 这边使用brave的方法将数据发送给zipkin
      # 其它方法See https://github.com/openzipkin/zipkin-reporter-java/tree/master
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      # 采样率
      probability: 1
# See https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging
# 只在没有独立的日志配置下生效
logging:
  pattern:
     level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
