spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: true
    database: MYSQL
    hibernate:
      ddlAuto: update

  redis:
    host: 127.0.0.1
    port: 6379