spring:
  # spring推荐使用spring.config.import,它由三个部分组成:[optional:]<configserver:|file:|classpath:>[url],configserver表示从配置中心读取配置
  # 默认的import见 org.springframework.boot.context.config.ConfigDataEnvironment.DEFAULT_SEARCH_LOCATIONS
  config:
    import: 'optional:classpath:/'
  cloud:
    config:
      enabled: false

  application:
    name: demo-service-client

  boot:
    admin:
      client:
        enabled: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

server:
  port: 28080

# spring-admin需要配置这些
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:28761/eureka/
    enabled: true

---
# 使用spring config server 使用注册中心
spring:
  config:
    activate:
      on-profile: spring-cloud-config-eureka
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: true
      name: demo-service-client,business
      profile: test
      discovery:
        enabled: true
        serviceId: demo-config-server

---
# 使用spring config server 使用url
spring:
  config:
    # 可以直接带上配置中心的地址
    import: 'optional:configserver:http://127.0.0.1:28888'
    activate:
      on-profile: spring-cloud-config-url
  cloud:
    config:
      name: demo-service-client,business
      profile: test
      enabled: true
      # 如果spring.config.import有带url,那么这边的url可以省略
      uri: http://127.0.0.1:28888

---
# spring admin不使用注册中心
spring:
  config:
    activate:
      on-profile: spring-admin-client-url
  boot:
    admin:
      client:
        url: 'http://localhost:25010'
        enabled: true
eureka:
  client:
    enabled: false

---
# spring admin使用注册中心
spring:
  config:
    activate:
      on-profile: spring-admin-eureka
  boot:
    admin:
      client:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: logstash
logging:
  config: classpath:logback-logstash.xml
---
spring:
  config:
    activate:
      on-profile: filebeat
logging:
  config: classpath:logback-filebeat.xml