spring:
   application:
      name: demo-service-server
   autoconfigure:
      exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
   zipkin:
      enabled: false

eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:28761/eureka/
server:
   port: 28010
management:
   endpoints:
      web:
         exposure:
            include: '*'

